//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUILDLet.WOL.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUILDLet.WOL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon BUILDLet_WOL {
            get {
                object obj = ResourceManager.GetObject("BUILDLet_WOL", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   BUILDLet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigurationFileFolderName {
            get {
                return ResourceManager.GetString("ConfigurationFileFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WOL.conf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigurationFileName {
            get {
                return ResourceManager.GetString("ConfigurationFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BUILDLet Utilities\WOL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigurationFileUtilitiesFolder {
            get {
                return ResourceManager.GetString("ConfigurationFileUtilitiesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HistoryCount {
            get {
                return ResourceManager.GetString("HistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input MAC Address: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputMessageLabelContent {
            get {
                return ResourceManager.GetString("InputMessageLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendButtonContent {
            get {
                return ResourceManager.GetString("SendButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendCount {
            get {
                return ResourceManager.GetString("SendCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magic Packet [{0}] has been sent {1} time(s) successfully! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
    }
}
